apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: neurobridge-frontend-config
  namespace: neurobridge
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
