apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neurobridge-ingress
  namespace: neurobridge
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "neurobridge-ip"
    networking.gke.io/managed-certificates: "neurobridge-cert"
    networking.gke.io/v1beta1.FrontendConfig: "neurobridge-frontend-config"
spec:
  ingressClassName: gce
  rules:
    - host: neurobridge.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.neurobridge.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
