apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: neurobridge
spec:
  provider:
    gcpsm:
      projectID: "wise-vim-480800-n2"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa
            key: gcp_sa.json
